### ISSUE TITLE
Purchase Connector not working properly with Unity 2022.3.41 on Android API Level 34

### ISSUE THREAD

**Issue by tedo135** [AppsFlyerSDK/appsflyer-unity-purchase-connector#17]
### Environment
- **Unity Version:** 2022.3.41
- **Target Platform:** Android
- **API Level:** 34
- **AppsFlyer SDK Version:** 6.13.0
- **Purchase Connector Version:** 2.0.1
- **In App Purchasing Package:** 4.12.2
- **External Dependency Manager Package:** 1.2.181

I've got  same issue with this version too
###
- **AppsFlyer SDK Version:** 6.13.10
- **Purchase Connector Version:** 2.0.1
###
- **AppsFlyer SDK Version:** 6.14.3
- **Purchase Connector Version:** 2.0.2

### Issue Description
We're facing an issue with the AppsFlyer Purchase Connector where revenue data isn't being logged on the event dashboard. During a purchase attempt in our Unity project, a runtime exception error occurs when using the connector.

### Steps to Reproduce
1. Initialize the AppsFlyer SDK with standard configuration.
2. Make an in app purchase
3. Observe the following error:

Please advise on any potential workarounds or fixes that can be implemented to resolve this issue. Thank you for your assistance.

### Logcat Output
```
2024.08.15 12:43:03.601 27292 27495 Error AppsFlyer_6.13.0 [Other] [PurchaseConnector]: Failed to log new purchase

2024.08.15 12:43:03.601 27292 27495 Error AppsFlyer_6.13.0 java.lang.NoSuchFieldError: No field Companion of type Lkotlin/Result$Companion; in class Lkotlin/Result; or its superclasses (declaration of 'kotlin.Result' appears in /data/app/~~JHXDNuqmT6t4yGSB1DYvAg==/com.happytools.learning.kids.games-9aCeIJ8q55k6gbQ6TCqAyw==/base.apk)

2024.08.15 12:43:03.601 27292 27495 Error AppsFlyer_6.13.0 	at com.appsflyer.internal.connector.purcahse.AFPurchaseConnectorA1v$14469.toJsonMap(:208)
2024.08.15 12:43:03.601 27292 27495 Error AppsFlyer_6.13.0 	at com.appsflyer.internal.connector.purcahse.AFPurchaseConnectorA1v$14469.getOneTimePurchaseOfferDetails(:197)
2024.08.15 12:43:03.601 27292 27495 Error AppsFlyer_6.13.0 	at com.appsflyer.internal.connector.purcahse.AFPurchaseConnectorA1v$14469.getQuantity(:135)
2024.08.15 12:43:03.601 27292 27495 Error AppsFlyer_6.13.0 	at com.appsflyer.internal.connector.purcahse.AFPurchaseConnectorA1v$14469.InAppPurchaseEvent(:27)
2024.08.15 12:43:03.601 27292 27495 Error AppsFlyer_6.13.0 	at java.lang.reflect.Method.invoke(Native Method)
2024.08.15 12:43:03.601 27292 27495 Error AppsFlyer_6.13.0 	at com.appsflyer.internal.connector.purcahse.AFPurchaseConnectorA1v$14469$AFPurchaseConnectorA1y.toJsonMap(:465)
2024.08.15 12:43:03.601 27292 27495 Error AppsFlyer_6.13.0 	at com.appsflyer.internal.connector.purcahse.AFPurchaseConnectorA1t.onProductDetailsResponse(:101)
2024.08.15 12:43:03.601 27292 27495 Error AppsFlyer_6.13.0 	at com.android.billingclient.api.BillingClientImpl.zzn(com.android.billingclient:billing@@6.2.1:504)
2024.08.15 12:43:03.601 27292 27495 Error AppsFlyer_6.13.0 	at com.android.billingclient.api.zzaj.call(com.android.billingclient:billing@@6.2.1:7)
2024.08.15 12:43:03.601 27292 27495 Error AppsFlyer_6.13.0 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024.08.15 12:43:03.601 27292 27495 Error AppsFlyer_6.13.0 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2024.08.15 12:43:03.601 27292 27495 Error AppsFlyer_6.13.0 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
2024.08.15 12:43:03.601 27292 27495 Error AppsFlyer_6.13.0 	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by tedo135** [comment]
We were missing `-keep class kotlin.** { *; }` in our ProGuard file. After reaching out Appsflyer support they were able to help me with this information.
